import type React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import { ThemeProvider } from "next-themes";
import { Navbar } from "@/components/navbar";
import { Sidebar } from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} antialiased 
          bg-[#FEFEFE] text-black 
          dark:bg-[#FFFF] dark:text-white 
        `}
      >
         {/* remove theme proqvider for now 
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        </ThemeProvider>
        */}
          <div className="flex flex-col h-screen">
            {/* Fixed Navbar */}
            <div className="flex-shrink-0">
              <Navbar />
            </div>

            {/* Main content with sidebar and scrollable main */}
            <div className="flex flex-1 overflow-hidden">
              {/* Fixed Sidebar - Left */}
              <div className="flex-shrink-0 w-64 hidden md:block">
                <Sidebar />
              </div>
              {/* Main and SocialFeed - Center and Right */}
              <div className="flex flex-1 overflow-hidden">
                {/* Scrollable main content */}
                <main className="flex-1 overflow-y-auto p-4 w-full bg-gray-50 dark:bg-[#FFFFF] text-black dark:text-white">
                  {children}
                </main>
              </div>
            </div>
          </div>
      </body>
    </html>
  );
}
